server:
  port: 8088
spring:
  application:
    name: blog-restapi
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app
    username: root
    password: mayanksql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:

    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQL8Dialect